"""created fundraiser db

Revision ID: 129e1dc4d469
Revises: 5d5920612e69
Create Date: 2022-09-29 12:04:07.655929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129e1dc4d469'
down_revision = '5d5920612e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundraisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fund_goal', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('fundraiser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fundraiser_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'description')
    op.drop_column('users', 'goal_amount')
    op.drop_column('users', 'current_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_amount', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('goal_amount', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('description', sa.TEXT(), nullable=True))
    op.drop_table('fundraisers')
    # ### end Alembic commands ###
