"""empty message

Revision ID: 3da71f976bef
Revises: c542d9bdc351
Create Date: 2022-09-29 16:20:30.816244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da71f976bef'
down_revision = 'c542d9bdc351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_amount', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
