"""fixed

Revision ID: 62544d9e55a1
Revises: 3da71f976bef
Create Date: 2022-09-29 16:21:18.180516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62544d9e55a1'
down_revision = '3da71f976bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundraiser', sa.Column('fund_goal', sa.Integer(), nullable=True))
    op.add_column('fundraiser', sa.Column('raised_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundraiser', 'raised_amount')
    op.drop_column('fundraiser', 'fund_goal')
    # ### end Alembic commands ###
