"""restart

Revision ID: a08c86564aaf
Revises: ac8e3d6d8f5e
Create Date: 2022-09-29 14:25:49.746452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08c86564aaf'
down_revision = 'ac8e3d6d8f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fundraisers')
    op.add_column('users', sa.Column('goal_amount', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('current_amount', sa.Integer(), nullable=True))
    op.drop_column('users', 'raised_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('raised_amount', sa.INTEGER(), nullable=True))
    op.drop_column('users', 'current_amount')
    op.drop_column('users', 'goal_amount')
    op.create_table('fundraisers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('fund_goal', sa.INTEGER(), nullable=True),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('fundraiser_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['fundraiser_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
