"""created fundraiser db2

Revision ID: ac8e3d6d8f5e
Revises: 129e1dc4d469
Create Date: 2022-09-29 12:09:47.545332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8e3d6d8f5e'
down_revision = '129e1dc4d469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('raised_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'raised_amount')
    # ### end Alembic commands ###
