"""added foreigkey

Revision ID: af3e65b9adf2
Revises: 62544d9e55a1
Create Date: 2022-09-30 12:01:42.763988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3e65b9adf2'
down_revision = '62544d9e55a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundraiser', sa.Column('fundraiser_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fundraiser', 'users', ['fundraiser_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fundraiser', type_='foreignkey')
    op.drop_column('fundraiser', 'fundraiser_id')
    # ### end Alembic commands ###
