"""fix data2

Revision ID: bdcaa6ddc0d4
Revises: e134d1c7c093
Create Date: 2022-09-29 15:46:22.744387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdcaa6ddc0d4'
down_revision = 'e134d1c7c093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'goal_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('goal_amount', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
