"""Added current goal amount

Revision ID: c168a3460baf
Revises: 8f43fed68da0
Create Date: 2022-09-27 22:09:32.483964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c168a3460baf'
down_revision = '8f43fed68da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('goal_amount', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('current_amount', sa.Integer(), nullable=True))
    op.drop_column('users', 'fund_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fund_amount', sa.INTEGER(), nullable=True))
    op.drop_column('users', 'current_amount')
    op.drop_column('users', 'goal_amount')
    # ### end Alembic commands ###
