"""update database

Revision ID: fb280c2abbbe
Revises: 478afe429887
Create Date: 2022-10-25 12:44:00.555832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb280c2abbbe'
down_revision = '478afe429887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundraiser', sa.Column('num_of_donors', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundraiser', 'num_of_donors')
    # ### end Alembic commands ###
