"""create date and time db

Revision ID: fc6ed569a35f
Revises: 1835d7dca143
Create Date: 2022-10-19 20:31:44.043833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc6ed569a35f'
down_revision = '1835d7dca143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donors', sa.Column('time_donated', sa.String(length=128), nullable=True))
    op.add_column('fundraiser', sa.Column('time_created', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('time_added', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'time_added')
    op.drop_column('fundraiser', 'time_created')
    op.drop_column('donors', 'time_donated')
    # ### end Alembic commands ###
